version: '3.7'

volumes:
  qw_learning-ms_db-storage:
    name: LearningMS-DB-Storage

networks:
  qw_learning-ms_internal-communications:
    name: qw_learning-ms_internal-communications
    ipam:
      config:
        - subnet: 159.87.0.0/16
  qw_learning-ms_db-access:
    name: qw_learning-ms_db-access
  qw_learning-ms_entry-point:
    name: qw_learning-ms_entry-point

services:
  qw_learning-ms_web-server:
    container_name: qw-learning-ms-nginx
    image: nginx:latest
    restart: unless-stopped
    networks:
      qw_learning-ms_internal-communications:
        ipv4_address: 159.87.173.80
      qw_learning-ms_entry-point:
        aliases:
          - learning.ms
    depends_on:
      - qw_learning-ms_process-manager
    volumes:
      - ./docker/virtual-host.conf:/etc/nginx/conf.d/default.conf
      - ./docker/ssl:/etc/ssl/certs
      - .:/var/www

  qw_learning-ms_db:
    container_name: qw-learning-ms-mysql
    image: mysql:5.7.40
    restart: unless-stopped
    networks:
      - qw_learning-ms_db-access
    volumes:
      - qw_learning-ms_db-storage:/var/lib/mysql
    env_file:
      - ./docker/db.env

  qw_learning-ms_process-manager:
    container_name: qw-learning-ms-php
    image: blackmaizegod/php-fpm:8.2
    restart: unless-stopped
    networks:
      - qw_learning-ms_db-access
      - qw_learning-ms_internal-communications
    depends_on:
      - qw_learning-ms_db
    links:
      - qw_learning-ms_db:db
    volumes:
      - .:/var/www
    environment:
      - XDEBUG_HOST=159.87.0.1
      - COMPOSER_VERSION=2